
-- Data Source=DESKTOP-C46S740\SQLEXPRESS;Integrated Security=True;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=False; --

DROP DATABASE Restaurants;
CREATE DATABASE Restaurants;

USE Restaurants;

DROP TABLE Restaurant;
CREATE TABLE Restaurant(
	Id INT NOT NULL IDENTITY,
	Name VARCHAR(255) NOT NULL,
	Street_addr VARCHAR(255) NOT NULL,
	City VARCHAR(255) NOT NULL,
	State VARCHAR(255) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE Cuisine(
	Id int NOT NULL IDENTITY,
	Name VARCHAR(255) NOT NULL,
	RestId INT NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(RestID) REFERENCES Restaurant(Id)
);

CREATE TABLE RestConnCuisine(
	Id INT NOT NULL,
	RestID INT NOT NULL,
	CuisineID INT NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(RestID) REFERENCES Restaurant(Id),
	FOREIGN KEY(CuisineID) REFERENCES Cuisine(Id)
);

ALTER TABLE Menu DROP CONSTRAINT RestId;

DROP TABLE Menu;

CREATE TABLE Menu(
	Id INT NOT NULL IDENTITY,
	Name VARCHAR(255) NOT NULL,
	Price decimal(18, 2) NOT NULL,
	RestId INT NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(RestId) REFERENCES Restaurant(Id)
);

ALTER TABLE Score DROP CONSTRAINT RestId;

DROP TABLE Score;
CREATE TABLE Score(
	Id INT NOT NULL IDENTITY,
	Score INT NOT NULL,
	date_submit DATE NOT NULL,
	RestId INT NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(RestId) REFERENCES Restaurant(Id)
);

ALTER TABLE Grade DROP CONSTRAINT Restaurant_id;

DROP TABLE Grade;
CREATE TABLE Grade(
	Id INT NOT NULL IDENTITY,
	Grade CHAR NOT NULL,
	RestId INT NOT NULL,
	PRIMARY KEY(Id),
	FOREIGN KEY(RestId) REFERENCES Restaurant(Id)
);


SELECT * FROM Restaurant;
SELECT * FROM Menu;
SELECT * FROM Score;
SELECT * FROM Grade;
